# Generated by Django 4.0.1 on 2022-01-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
